apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatcar-google-image-uploader
spec:
  selector:
    matchLabels:
      app: flatcar-google-image-uploader
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flatcar-google-image-uploader
    spec:
      containers:
        - name: uploader
          image: quay.io/utilitywarehouse/flatcar-google-image-uploader
          volumeMounts:
            - name: gcp-credentials
              mountPath: /credentials.json
              subPath: credentials.json
      volumes:
        - name: gcp-credentials
          secret:
            secretName: flatcar-google-image-uploader
            defaultMode: 500
