apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  # - github.com/utilitywarehouse/flatcar-google-image-uploader//manifests/base
patchesStrategicMerge:
  - flatcar-google-image-uploader-patch.yaml
secretGenerator:
  - name: flatcar-google-image-uploader
    files:
      - credentials.json=secrets/flatcar-google-image-uploader-credentials.json
